apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ubuntu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ubuntu
  template:
    metadata:
      labels:
        app: nginx-ubuntu
    spec:
      volumes:
      - name: shared-img-folder
        emptyDir: {}

      containers:
      - name: nginx-container
        image: nginx
        volumeMounts:
        - name: shared-img-folder
          mountPath: /usr/share/nginx/html/img

      - name: ubuntu-container
        image: mlmerchant/letter-board
        volumeMounts:
        - name: shared-img-folder
          mountPath: /img

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30007
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ubuntu
